version: '3.8'
services:
  xtls-reality:
    build:
        context: .
        dockerfile: Dockerfile
    image:  xtls-reality
    environment:
      - SNI=bladebla.cz
      - SHORT_ID=47a28d43
    container_name: xtls-reality
    restart: always
    ports:
      - "127.0.0.1:8443:443"
    volumes:
      - xtls-reality-volume:/opt/xray/config
volumes:
  xtls-reality-volume:
